import React from "react";
import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import { Providers } from "../providers/Providers";
import { Navbar } from "../components/navbar/Navbar";
import { PageAnimation } from "@/components/helpers/PageAnimation";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en" className="dark">
                <body className={`${inter.className}`}>
                    <Navbar />
                    <main className="mx-auto flex max-w-7xl flex-col items-center justify-center gap-24 p-24">
                        <PageAnimation>{children}</PageAnimation>
                    </main>
                    <Toaster richColors />
                </body>
            </html>
        </Providers>
    );
}
