import React from "react";
import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import { Providers } from "../providers/Providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en" className="dark">
                <body className={`${inter.className}`}>
                    <main className="flex flex-col justify-center items-center p-24">
                        {children}
                    </main>
                </body>
            </html>
        </Providers>
    );
}
